/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { TestStorageAccount__factory } from "./TestStorageAccount__factory";
export { TestStorageAccountFactory__factory } from "./TestStorageAccountFactory__factory";
