/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TestStorageAccount } from "./TestStorageAccount";
export type { TestStorageAccountFactory } from "./TestStorageAccountFactory";
