/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TestTimeRangeAccount } from "./TestTimeRangeAccount";
export type { TestTimeRangeAccountFactory } from "./TestTimeRangeAccountFactory";
