/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TestOpcodesAccount } from "./TestOpcodesAccount";
export type { TestOpcodesAccountFactory } from "./TestOpcodesAccountFactory";
