/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TestRuleAccount } from "./TestRuleAccount";
export type { TestRuleAccountFactory } from "./TestRuleAccountFactory";
