version: "3.8"

services:
  rundler:
    image: truewallet/rundler
    ports:
      # RPC port
      - "3000:3000"
      # Metrics port
      - "8080:8080"
    environment:
      - ENTRY_POINTS=0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789
      - NODE_HTTP=https://base-goerli.publicnode.com
      - CHAIN_ID=84531
      - BUILDER_PRIVATE_KEY=0xdbe2b933bb7d57444cdba9c71b5ceb79b60dc455ad691d856e6e4025cf542caa
