/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { TestOpcodesAccount__factory } from "./TestOpcodesAccount__factory";
export { TestOpcodesAccountFactory__factory } from "./TestOpcodesAccountFactory__factory";
