/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { TestTimeRangeAccount__factory } from "./TestTimeRangeAccount__factory";
export { TestTimeRangeAccountFactory__factory } from "./TestTimeRangeAccountFactory__factory";
